### ISSUE TITLE
[REFACTOR] 댓글 기능 리팩토링 및 정규화

### ISSUE THREAD

**Issue by ywj9811** [KUSITMS-27-chilling/Dachae-BE#131]
## Description
- 댓글 컨트롤러 및 서비스 분리
- 정규화를 통한 Repository 참조 줄이기

## Todo
- [ ] 댓글 컨트롤러 분리
- [ ] 댓글 서비스 분리
- [ ] 정규화 고민
- [ ] 정규화 완료 or 철회
- [ ] 구현 완료

## Etc
정규화를 통해 더 간단한 방식이 있을 지 고민
