### ISSUE TITLE
[FEAT] 배움 소식 구현

### ISSUE THREAD

**Issue by ywj9811** [KUSITMS-27-chilling/Dachae-BE#144]
## Description
같이 들어요 참여자 발생 시
같이 들어요 목표치 완료 시

## Todo

- [ ] 같이 들어요 누군가 참여하면 redis에 저장
- [ ] 같이 들어요 목표치 완료하면 저장할 때 isFin = True
- [ ] 배움 소식 조회
- [ ] 동작 확인

**Comment by ywj9811** [comment]
- 1차 완성
- 검토중
