### ISSUE TITLE
[FIX] 알림 형식 변경

### ISSUE THREAD

**Issue by ywj9811** [KUSITMS-27-chilling/Dachae-BE#145]
## Description
기존의 알림은 백에서도 프론트에서도 처리하기 너무 어려운 형식으로 반환됨

## Todo

- [x] 알람 처리 방식 정립
- [x] 강의 후기 댓글 알림 처리
- [x] 자유 게시판 댓글 알림 처리
- [x] 같이 들어요 댓글 알림 처리
- [x] 조회 처리
- [x] 변경 확인 및 동작 확인

**Comment by ywj9811** [comment]
- 잘못 동작하는 중
