### ISSUE TITLE
[FIX, BUG] 댓글 알림 동작 오류 해결 

### ISSUE THREAD

**Issue by ywj9811** [KUSITMS-27-chilling/Dachae-BE#153]
## Description
- 댓글 1개 달면 2개씩 알림이 오는 중
- 추가로 mention을 추가할 경우 올바르게 가는지 확인해야함 올바르게 알림이 전송되지 않는 것 같음

- 확인 결과 mention을 추가하면 게시글 작성자에게 2개의 알림이 가고 태그된 사람에게는 아무런 알림이 가지 않음
- 작성자에게는 태그 정보X 댓글 알림, 태그된 사람에게는 태그 알림이 가도록 수정해야

## Todo

- [x] 댓글 1개 달면 2개씩 알림이 가는 오류 해결
- [x] mention 추가시 올바르게 동작 하는지 확인
- [x] 오류 해결 완료시 동작 확인
